### ISSUE TITLE
语音识别模型私有化部署后，按文档中心内容操作，依然无法运行，请问代码里是缺少必要的参数吗？ 请帮助下

### ISSUE THREAD

**Issue by cuiyingbao** [alibaba-damo-academy/FunASR#643] opened 2023-06-16 02:17 UTC
执行代码为：
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from modelscope.models import Model
model = Model.from_pretrained('damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch')
inference_pipeline = pipeline(
            task=Tasks.auto_speech_recognition,
                model=model,
                    model_revision="v1.2.4")
rec_result = inference_pipeline(audio_in='006.wav')
print(rec_result['text'])

以下为报错信息：
2023-06-16 09:55:00,401 - modelscope - INFO - PyTorch version 1.11.0+cu113 Found.
2023-06-16 09:55:00,404 - modelscope - INFO - Loading ast index from /mnt/workspace/.cache/modelscope/ast_indexer
2023-06-16 09:55:00,450 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 0712ab6e70fd62c615c3fd4ba2a51acd and a total number of 849 components indexed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/conda/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/conda/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f32db8d5610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions?EndTime=1684425540 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f32db8d5610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "offline.py", line 11, in <module>
    preprocessor = Preprocessor.from_pretrained('damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch',config_file = "/mnt/workspace/.cache/modelscope/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/configuration.json")
  File "/opt/conda/lib/python3.7/site-packages/modelscope/preprocessors/base.py", line 266, in from_pretrained
    '.*.index',
  File "/opt/conda/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 95, in snapshot_download
    model_id, revision=revision, cookies=cookies)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/hub/api.py", line 466, in get_valid_revision
    use_cookies=False if cookies is None else cookies)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/hub/api.py", line 431, in list_model_revisions
    r = self.session.get(path, cookies=cookies, headers=self.headers)
  File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions?EndTime=1684425540 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f32db8d5610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
root@localhost:/home/offline# vim offline.py 
root@localhost:/home/offline# python offline.py 
2023-06-16 09:58:40,585 - modelscope - INFO - PyTorch version 1.11.0+cu113 Found.
2023-06-16 09:58:40,587 - modelscope - INFO - Loading ast index from /mnt/workspace/.cache/modelscope/ast_indexer
2023-06-16 09:58:40,633 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 0712ab6e70fd62c615c3fd4ba2a51acd and a total number of 849 components indexed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/conda/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/conda/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2a29974610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 828, in urlopen
    **response_kw
  File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions?EndTime=1684425540 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a29974610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "offline.py", line 14, in <module>
    model = Model.from_pretrained('damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch',config_file = "/mnt/workspace/.cache/modelscope/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/configuration.json")
  File "/opt/conda/lib/python3.7/site-packages/modelscope/models/base/base_model.py", line 117, in from_pretrained
    model_name_or_path, revision, user_agent=invoked_by)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 95, in snapshot_download
    model_id, revision=revision, cookies=cookies)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/hub/api.py", line 466, in get_valid_revision
    use_cookies=False if cookies is None else cookies)
  File "/opt/conda/lib/python3.7/site-packages/modelscope/hub/api.py", line 431, in list_model_revisions
    r = self.session.get(path, cookies=cookies, headers=self.headers)
  File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.modelscope.cn', port=80): Max retries exceeded with url: /api/v1/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/revisions?EndTime=1684425540 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a29974610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by lyblsgo** [comment] 2023-06-16 02:26
This error message indicates that there was a temporary failure in resolving the DNS (Domain Name System) entry for the host that the code was trying to connect to. This could be due to a variety of reasons, such as network issues, DNS server issues, or problems with the host itself.

To resolve this issue, you could try the following steps:

Check your internet connection and ensure that you are connected to the network.
Verify that the DNS server settings on your computer are correct.
Try pinging the host to see if the issue is with the host itself.
Wait for a few minutes and try running the code again, as the issue may be temporary.

**Comment by cuiyingbao** [comment] 2023-06-16 02:26
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed** 2023-08-08 11:42 UTC
